# Prometheus configuration file
global:
  scrape_interval: 3s      # real-time updates every 3 seconds

scrape_configs:

  - job_name: 'node_local'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'node_remote'
    static_configs:
      - targets:
          - '10.0.0.1:9100'
